install:
	./gradlew clean install

check-updates:
	./gradlew dependencyUpdates

run:
	./gradlew clean
	./gradlew run

lint:
	./gradlew checkstyleMain

build:
	./gradlew clean build

report:
	./gradlew jacocoTestReport

.PHONY: build